=== demon1976/StateMachineGenerated/StateMachine.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- 
     author: Dima Wedel (dwl): dwedel@jetter.de
     date: 26.01.2016
     version: 1.0
     
     State machine for Motion Control (MC)
-->
<xs:schema xmlns="http://www.demo.com"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:mstns="http://www.demo.com"
    targetNamespace="http://www.demo.com"
    elementFormDefault="qualified" version="1.0" id="demo">
  
  <xs:annotation>
    <xs:documentation xml:lang="DE" />
  </xs:annotation>

  <xs:element name="StateMachine" type="StateMachineType" />
  
  <xs:complexType name="StateMachineType">
    <xs:sequence>
      <xs:element name="Include" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="ForwardDeclaration" type="ForwardDeclarationType" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="Events" type="EventIdListType"/>
      <xs:element name="Enum" type="EnumType" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="StartState" type="StateIdType"/>
      <xs:element name="State" type="StateType" minOccurs="2" maxOccurs="unbounded"/>
      <!--
            All member data and functions are private. 
            "protected" makes no sence because there musn't be derivation of it.
            "public" is forbidden because otherwise th people will define it that way but this 
            is the wrong way to use FSM.
      -->
      <xs:element name="MemberFunction" type="FunctionType" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="MemberData" type="DataTypeMember" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="Name" type="xs:string" use="required" />
    <xs:attribute name="Namespace" type="xs:string" use="required" />
    <xs:attribute name="GenerateForChange" type="xs:boolean" use="required" />
  </xs:complexType>

  <xs:simpleType name="ForwardDeclarationType">
    <xs:restriction base="xs:string">
      <xs:pattern value="struct [a-zA-Z]{1}([a-zA-Z0-9_])*|class [a-zA-Z]{1}([a-zA-Z0-9_])*"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="EventIdListType">
    <xs:sequence>
      <xs:element name="Event" type="EventIdType" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  
  <xs:simpleType name="EventIdType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z]+[A-Z0-9_]*" />
    </xs:restriction>
  </xs:simpleType>
  
  <xs:complexType name="EnumType">
    <xs:sequence>
      <xs:element name="EnumEntry" type="EnumEntryType" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="EnumName" type="xs:string" use="required" />
    <xs:attribute name="Comment" type="xs:string" use="optional" />
  </xs:complexType>

  <xs:simpleType name="EnumEntryType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z]+[A-Z0-9_]*" />
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="StateIdType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z]+[A-Z0-9_]*" />
    </xs:restriction>
  </xs:simpleType>
  
  <xs:complexType name="StateType">
    <xs:sequence>
      <xs:element name="Dispatch" type="DispatchFunctionType" minOccurs="1" maxOccurs="1"/>
      <!--
            All member data and functions are private. 
            "protected" makes no sence because there musn't be derivation of it.
            "public" is forbidden because otherwise th people will define it that way but this 
            is the wrong way to use FSM.
      -->
      <xs:element name="MemberFunction" type="FunctionType" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="MemberData" type="DataTypeMember" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="Name" type="StateIdType" use="required" />
    <xs:attribute name="Comment" type="xs:string" use="optional" />
    <xs:attribute name="EnterRoutine" type="xs:string" use="optional" />
    <xs:attribute name="LeaveRoutine" type="xs:string" use="optional" />
    <xs:attribute name="SuperState" type="StateIdType" use="required" />
    <xs:attribute name="StartSubState" type="StateIdType" use="optional" />
    <xs:attribute name="WithHistory" type="xs:boolean" use="required" />
  </xs:complexType>
  
  <xs:complexType name="DispatchFunctionType">
    <xs:sequence>
      <xs:element name="Subroutine" type="SubroutineType" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="SubroutineType">
    <xs:sequence>
      <xs:element name="Transition" type="TransitionType" minOccurs="1" maxOccurs="1"/>
      <xs:element name="Condition" type="DecisionFuncTypeWithoutParams" minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
    <xs:attribute name="EventId" type="EventIdType" use="required" />
  </xs:complexType>

  <xs:complexType name="TransitionType">
    <xs:sequence>
      <xs:element name="Routine" type="ProcedureTypeWithoutParams" minOccurs="0" maxOccurs="1" />
    </xs:sequence>
    <xs:attribute name="Destination" type="StateIdType" use="required" />
  </xs:complexType>

  <xs:complexType name="FunctionType">
    <xs:sequence>
      <xs:element name="Parameter" type="DataTypeParameter" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="ReturnType" type="xs:string" use="required" />
    <xs:attribute name="Name" type="xs:string" use="required" />
    <xs:attribute name="IsConst" type="xs:boolean" use="required" />
    <xs:attribute name="KindOfVisibility" type="VisibilityType" use="required" />
    <xs:attribute name="Comment" type="xs:string" use="optional" />
  </xs:complexType>

  <xs:simpleType name="VisibilityType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="public"/>
      <xs:enumeration value="protected"/>
      <xs:enumeration value="private"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="DataTypeMember">
    <xs:sequence/>
    <xs:attribute name="Name" type="xs:string" use="required" />
    <xs:attribute name="Type" type="xs:string" use="required" />
    <xs:attribute name="InitialValue" type="xs:string" use="required" />
    <xs:attribute name="Comment" type="xs:string" use="optional" />
  </xs:complexType>

  <xs:complexType name="DataTypeParameter">
    <xs:sequence/>
    <xs:attribute name="Name" type="xs:string" use="required" />
    <xs:attribute name="Type" type="xs:string" use="required" />
  </xs:complexType>

  <xs:complexType name="ProcedureTypeWithoutParams">
    <xs:sequence/>
    <xs:attribute name="Name" type="xs:string" use="required" />
  </xs:complexType>

  <xs:complexType name="DecisionFuncTypeWithoutParams">
    <xs:sequence/>
    <xs:attribute name="Name" type="xs:string" use="required" />
  </xs:complexType>

	
</xs:schema>

=== demon1976/StateMachineGenerated/MotionHome.xml
<?xml version="1.0" encoding="utf-8" ?>
<!-- 
     author: Dima Wedel (dwl): dwedel@jetter.de
     date: 16 nov 2016
     version: 1.0
-->
<StateMachine xmlns="http://www.demo.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.demo.com StateMachine.xsd"
Name="MotionHomeSM" Namespace="MotionHome" GenerateForChange="true">
  <Include>src/OS.h</Include>
  <Include>src/OS_Queue.h</Include>
  <ForwardDeclaration>class BlaClass</ForwardDeclaration>
  <ForwardDeclaration>struct qqq</ForwardDeclaration>
  <Events>
    <Event>CYCLIC_EVENT</Event>
    <Event>DRIVE_READ_DATA</Event>
    <Event>PARAM_UPDATE_HOMING</Event>
    <Event>AXIS_USER_REF_START</Event>
    <Event>AXIS_USER_REF_SET</Event>
    <Event>AXIS_USER_REF_HALT</Event>
    <Event>AXIS_STOPPED</Event>
    <Event>CAM_DETECTED</Event>
    <Event>K0_DETECTED</Event>
  </Events>
  <Enum EnumName="KIND_REFERENCE_MARK" Comment="options for reference mark">
    <EnumEntry>UNDEFINED_REF_MARK</EnumEntry>
    <EnumEntry>ZERO_MARK</EnumEntry>
    <EnumEntry>SLOPE</EnumEntry>
  </Enum>
  <Enum EnumName="NUMBER_PHASE" Comment="describes how many phases should the motion home take ">
    <EnumEntry>UNDEFINED_PHASE_NUMBER</EnumEntry>
    <EnumEntry>ONE</EnumEntry>
    <EnumEntry>TWO</EnumEntry>
  </Enum>
  <Enum EnumName="SLOPE_POSITION_TO_SEARCH" Comment="What is the current slope position to search">
    <EnumEntry>UNDEFINED_SLOPE_POSITION</EnumEntry>
    <EnumEntry>NO_SLOPE</EnumEntry>
    <EnumEntry>REF_SWITCH_LEFT</EnumEntry>
    <EnumEntry>REF_SWITCH_RIGHT</EnumEntry>
    <EnumEntry>NEGATIVE_SWITCH</EnumEntry>
    <EnumEntry>POSITIVE_SWITCH</EnumEntry>
  </Enum>
  <Enum EnumName="KIND_OF_SLOPE" Comment="What is the current slope to search">
    <EnumEntry>UNDEFINED_KIND_OF_SLOPE</EnumEntry>
    <EnumEntry>HIGH_LEFT</EnumEntry>
    <EnumEntry>LOW_LEFT</EnumEntry>
    <EnumEntry>HIGH_RIGHT</EnumEntry>
    <EnumEntry>LOW_RIGHT</EnumEntry>
    <EnumEntry>HIGH_NEGATIVE</EnumEntry>
    <EnumEntry>HIGH_POSITIVE</EnumEntry>
    <EnumEntry>LOW_NEGATIVE</EnumEntry>
    <EnumEntry>LOW_POSITIVE</EnumEntry>
  </Enum>
  <Enum EnumName="SWITCH_STATE" Comment="describes the axis position in relation to switch">
    <EnumEntry>UNDEFINED_SWITCH_STATE</EnumEntry>
    <EnumEntry>OFF_SWITCH</EnumEntry>
    <EnumEntry>ON_MIDDLE_SWITCH</EnumEntry>
    <EnumEntry>ON_NEGATIVE_SWITCH</EnumEntry>
    <EnumEntry>ON_POSITIVE_SWITCH</EnumEntry>
  </Enum>
  <Enum EnumName="ERROR_TYPE" Comment="which error could happen">
    <EnumEntry>UNDEFINED_ERROR_TYPE</EnumEntry>
  </Enum>
  <StartState>WORKING</StartState>
  <State Name="WORKING" SuperState="ROOT" StartSubState="START_FINISH" WithHistory="false" Comment="super state for working part">
    <Dispatch>
      <Subroutine EventId="CYCLIC_EVENT">
        <Transition Destination="ERROR"/>
        <Condition Name="isErrorOccured"/>
      </Subroutine>
    </Dispatch>
  </State>
  <State Name="START_FINISH" SuperState="WORKING" EnterRoutine="resetMember" WithHistory="false" Comment="the SM starts and ends here">
    <Dispatch>
      <Subroutine EventId="CYCLIC_EVENT">
        <Transition Destination="EXTERNAL"/>
        <Condition Name="isExternalAxisAndMotionHomeActive"/>
      </Subroutine>
      <Subroutine EventId="CYCLIC_EVENT">
        <Transition Destination="MOTION_HOME_ONGOING">
          <Routine Name="startMotionHome"/>
        </Transition>
        <Condition Name="isMotionHomeActiveAndAxisHold"/>
      </Subroutine>
      <Subroutine EventId="CYCLIC_EVENT">
        <Transition Destination="START_FINISH">
          <Routine Name="processHoldOn"/>
        </Transition>
        <Condition Name="isMotionHomeActiveButAxisInMotion"/>
      </Subroutine>
      <Subroutine EventId="AXIS_USER_REF_START">
        <Transition Destination="START_FINISH">
          <Routine Name="processStartMotionHome"/>
        </Transition>
      </Subroutine>
      <Subroutine EventId="AXIS_USER_REF_SET">
        <Transition Destination="START_FINISH">
          <Routine Name="processSetMotionHome"/>
        </Transition>
      </Subroutine>
      <Subroutine EventId="PARAM_UPDATE_HOMING">
        <Transition Destination="START_FINISH">
          <Routine Name="updateParameters"/>
        </Transition>
      </Subroutine>
      <Subroutine EventId="CYCLIC_EVENT">
        <Transition Destination="SEND_REFERENCE_DATA_TO_DRIVE"/>
        <Condition Name="isSetReferenceActive"/>
      </Subroutine>
    </Dispatch>
    <MemberData Name="isStarted" Type="bool" InitialValue="false" Comment="is motion home started"/>
    <MemberData Name="isSet" Type="bool" InitialValue="false" Comment="is motion home (already) set"/>
    <MemberData Name="isExternal" Type="bool" InitialValue="false" Comment="is this an external axis?"/>
  </State>
  <State Name="MOTION_HOME_ONGOING" SuperState="WORKING" StartSubState="INIT" EnterRoutine="reset" WithHistory="false" Comment="handle all situations during running motion home">
    <Dispatch>
      <Subroutine EventId="AXIS_USER_REF_HALT">
        <Transition Destination="MOTION_HOME_ONGOING">
          <Routine Name="processHalt"/>
        </Transition>
      </Subroutine>
      <Subroutine EventId="AXIS_STOPPED">
        <Transition Destination="MOTION_HOME_ONGOING">
          <Routine Name="processAxisStopped"/>
        </Transition>
      </Subroutine>
    </Dispatch>
  </State>
  <State Name="INIT" SuperState="MOTION_HOME_ONGOING" EnterRoutine="saveValues" WithHistory="false" Comment="prepare everything to motion home procedure">
    <Dispatch>
      <Subroutine EventId="CYCLIC_EVENT">
        <Transition Destination="SEARCH_FOR_ZM">
          <Routine Name="startVzm"/>
        </Transition>
        <Condition Name="isZmOnly"/>
      </Subroutine>
      <Subroutine EventId="CYCLIC_EVENT">
        <Transition Destination="START_SLOW_MOTION"/>
        <Condition Name="isOnePhase"/>
      </Subroutine>
      <Subroutine EventId="CYCLIC_EVENT">
        <Transition Destination="START_OUTSIDE_REF_SWITCH">
          <Routine Name="setCorrectSlope"/>
        </Transition>
        <Condition Name="isOffSwitchAndTwoPhase"/>
      </Subroutine>
      <Subroutine EventId="CYCLIC_EVENT">
        <Transition Destination="START_ON_SWITCH"/>
        <Condition Name="isOnSwitchAndTwoPhase"/>
      </Subroutine>
    </Dispatch>
  </State>
  <State Name="START_OUTSIDE_REF_SWITCH" SuperState="MOTION_HOME_ONGOING" EnterRoutine="startVref" WithHistory="false" Comment="if  start mh outside of switch (usual case)">
    <Dispatch>
      <Subroutine EventId="CAM_DETECTED">
        <Transition Destination="START_OUTSIDE_REF_SWITCH">
          <Routine Name="processCamDetected"/>
        </Transition>
      </Subroutine>
      <Subroutine EventId="CYCLIC_EVENT">
        <Transition Destination="CORRECT_SWITCH_FAST_LOW_HIGH">
          <Routine Name="setCorrectNextSlope"/>
        </Transition>
        <Condition Name="isCorrectSwitch"/>
      </Subroutine>
      <Subroutine EventId="CYCLIC_EVENT">
        <Transition Destination="END_SWITCH_LOW_HIGH">
          <Routine Name="changeDirection"/>
        </Transition>
        <Condition Name="isMiddleSwitchButFoundHighSlopeForCorrectEndSwitch"/>
      </Subroutine>
    </Dispatch>
  </State>
  <State Name="START_ON_SWITCH" SuperState="MOTION_HOME_ONGOING" EnterRoutine="checkError" WithHistory="false" Comment="hgsi">
    <Dispatch>
      <Subroutine EventId="CYCLIC_EVENT">
        <Transition Destination="START_OUTSIDE_REF_SWITCH"/>
        <Condition Name="isWrongSwitch"/>
      </Subroutine>
      <Subroutine EventId="CYCLIC_EVENT">
        <Transition Destination="CORRECT_SWITCH_FAST_LOW_HIGH">
          <Routine Name="setCorrectNextSlope"/>
        </Transition>
        <Condition Name="isCorrectSwitch"/>
      </Subroutine>
    </Dispatch>
  </State>
  <State Name="END_SWITCH_LOW_HIGH" SuperState="MOTION_HOME_ONGOING" EnterRoutine="startVref" WithHistory="false" Comment="dhdhd">
    <Dispatch>
      <Subroutine EventId="CYCLIC_EVENT">
        <Transition Destination="END_SWITCH_LOW_HIGH">
          <Routine Name="setError"/>
        </Transition>
        <Condition Name="hasFoundAnotherEndSwitch"/>
      </Subroutine>
      <Subroutine EventId="CAM_DETECTED">
        <Transition Destination="END_SWITCH_LOW_HIGH">
          <Routine Name="processCamDetected"/>
        </Transition>
      </Subroutine>
      <Subroutine EventId="CYCLIC_EVENT">
        <Transition Destination="CORRECT_SWITCH_HIGH_LOW"/>
        <Condition Name="hasFoundCorrectSlope"/>
      </Subroutine>
    </Dispatch>
  </State>
  <State Name="CORRECT_SWITCH_FAST_LOW_HIGH" SuperState="MOTION_HOME_ONGOING" EnterRoutine="startWithVzmAndChangeDirection" WithHistory="false"  Comment="fjboidbh">
    <Dispatch>
      <Subroutine EventId="CYCLIC_EVENT">
        <Transition Destination="CORRECT_SWITCH_FAST_LOW_HIGH">
          <Routine Name="setError"/>
        </Transition>
        <Condition Name="notFoundCorrectSlope"/>
      </Subroutine>
      <Subroutine EventId="CAM_DETECTED">
        <Transition Destination="CORRECT_SWITCH_FAST_LOW_HIGH">
          <Routine Name="processCamDetected"/>
        </Transition>
      </Subroutine>
      <Subroutine EventId="CYCLIC_EVENT">
        <Transition Destination="CORRECT_SWITCH_HIGH_LOW"/>
        <Condition Name="foundCorrectSlope"/>
      </Subroutine>
    </Dispatch>
  </State>
  <State Name="START_SLOW_MOTION" SuperState="MOTION_HOME_ONGOING" EnterRoutine="startVzm" WithHistory="false" Comment="slow motion to find reference">
    <Dispatch>
      <Subroutine EventId="CYCLIC_EVENT">
        <Transition Destination="START_SLOW_MOTION">
          <Routine Name="setError"/>
        </Transition>
